
import { createPinia } from 'pinia'
import router from './router'
import type { App } from "vue";

import {
  createVuesticEssential,
  createIconsConfig,
  VaButton,
  VaButtonToggle,
  VaSplit,
  VaImage,
  VaModal,
  VaCardTitle,
  VaCardContent,
  VaCardActions,
  VaInput,
  VaNavbar,
  VaNavbarItem,
  VaOptionList,
  VaSelect,
  VaTreeView,
  VaProgressCircle,
  VaChip,
  VaIcon,
  VaCheckbox,
  VaDropdown,
  VaDropdownContent,
  VaButtonGroup,
  VaDivider,
  VaButtonDropdown,
  VaDataTable,
  VaToast,
  VaSidebar,
  VaList,
  VaListLabel,
  VaListItem,
  VaListItemSection,
  VaSidebarItem,
  VaSidebarItemContent,
  VaSidebarItemTitle,
  VaScrollContainer,
  VaListItemLabel,
  VaRadio,
  VaCollapse,
  VaColorInput,
  VaTextarea,
  VaSlider,
  VaPagination,
  VaCounter,
  VaSwitch,
  VaDateInput,
  VaTimeInput,
  VaTabs,
  VaTab,
  VaInnerLoading,
  VaFileUpload,
  type IconConfiguration,
} from "vuestic-ui";
import "vuestic-ui/css";

export function initVendors(app: App) {
  app.use(createPinia())
  app.use(router)

  const fonts: IconConfiguration[] = [
    {
        name: "mdi-{icon}",
        resolve: ({ icon }) => ({
            class: "material-icons-outlined",
            content: icon,
            tag: "span",
        }),
    },
  ];

  app.use(
    createVuesticEssential({
        components: {
            VaButton,
            VaButtonToggle,
            VaSplit,
            VaImage,
            VaModal,
            VaCardTitle,
            VaCardContent,
            VaCardActions,
            VaInput,
            VaNavbar,
            VaNavbarItem,
            VaOptionList,
            VaSelect,
            VaTreeView,
            VaProgressCircle,
            VaChip,
            VaIcon,
            VaCheckbox,
            VaDropdown,
            VaDropdownContent,
            VaButtonGroup,
            VaDivider,
            VaDataTable,
            VaToast,
            VaButtonDropdown,
            VaSidebar,
            VaSidebarItem,
            VaSidebarItemContent,
            VaSidebarItemTitle,
            VaScrollContainer,
            VaList,
            VaListLabel,
            VaListItem,
            VaListItemSection,
            VaListItemLabel,
            VaRadio,
            VaCollapse,
            VaColorInput,
            VaTextarea,
            VaSlider,
            VaPagination,
            VaCounter,
            VaSwitch,
            VaDateInput,
            VaTimeInput,
            VaTabs,
            VaTab,
            VaInnerLoading,
            VaFileUpload,
        },
        config: {
            colors: {
                variables: {
                    primary: "#133370",
                },
            },
            icons: createIconsConfig({ fonts }),
        },
    }),
  );
}